// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PrAnalysis struct {
	ID              int64              `json:"id"`
	RepoID          int64              `json:"repo_id"`
	PrNumber        int32              `json:"pr_number"`
	PrTitle         string             `json:"pr_title"`
	PrUrl           string             `json:"pr_url"`
	DiffUrl         string             `json:"diff_url"`
	Summary         pgtype.Text        `json:"summary"`
	RiskLevel       pgtype.Text        `json:"risk_level"`
	PossibleBugs    []byte             `json:"possible_bugs"`
	MissingTests    []byte             `json:"missing_tests"`
	Improvements    []byte             `json:"improvements"`
	RawResponse     []byte             `json:"raw_response"`
	Status          pgtype.Text        `json:"status"`
	Error           pgtype.Text        `json:"error"`
	GithubCommentID pgtype.Int8        `json:"github_comment_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Repository struct {
	ID        int64              `json:"id"`
	GithubID  int64              `json:"github_id"`
	FullName  string             `json:"full_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
