// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: pr_analyses.sql

package sqlc

import (
	"context"
)

const createPendingPRAnalysis = `-- name: CreatePendingPRAnalysis :one
INSERT INTO pr_analyses (
    repo_id,
    pr_number,
    pr_title,
    pr_url,
    diff_url,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'pending'
)
RETURNING id, repo_id, pr_number, pr_title, pr_url, diff_url, summary, risk_level, possible_bugs, missing_tests, improvements, raw_response, status, error, github_comment_id, created_at
`

type CreatePendingPRAnalysisParams struct {
	RepoID   int64  `json:"repo_id"`
	PrNumber int32  `json:"pr_number"`
	PrTitle  string `json:"pr_title"`
	PrUrl    string `json:"pr_url"`
	DiffUrl  string `json:"diff_url"`
}

func (q *Queries) CreatePendingPRAnalysis(ctx context.Context, arg CreatePendingPRAnalysisParams) (PrAnalysis, error) {
	row := q.db.QueryRow(ctx, createPendingPRAnalysis,
		arg.RepoID,
		arg.PrNumber,
		arg.PrTitle,
		arg.PrUrl,
		arg.DiffUrl,
	)
	var i PrAnalysis
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PrNumber,
		&i.PrTitle,
		&i.PrUrl,
		&i.DiffUrl,
		&i.Summary,
		&i.RiskLevel,
		&i.PossibleBugs,
		&i.MissingTests,
		&i.Improvements,
		&i.RawResponse,
		&i.Status,
		&i.Error,
		&i.GithubCommentID,
		&i.CreatedAt,
	)
	return i, err
}
