// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreatePendingPRAnalysis(ctx context.Context, arg CreatePendingPRAnalysisParams) (PrAnalysis, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	GetRepositoryByGitHubID(ctx context.Context, githubID int64) (Repository, error)
	UpdateRepositoryFullName(ctx context.Context, arg UpdateRepositoryFullNameParams) (Repository, error)
}

var _ Querier = (*Queries)(nil)
