// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: repositories.sql

package sqlc

import (
	"context"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (
    github_id,
    full_name
) VALUES (
    $1,
    $2
)
RETURNING id, github_id, full_name, created_at
`

type CreateRepositoryParams struct {
	GithubID int64  `json:"github_id"`
	FullName string `json:"full_name"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository, arg.GithubID, arg.FullName)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}

const getRepositoryByGitHubID = `-- name: GetRepositoryByGitHubID :one
SELECT id, github_id, full_name, created_at
FROM repositories
WHERE github_id = $1
`

func (q *Queries) GetRepositoryByGitHubID(ctx context.Context, githubID int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByGitHubID, githubID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}

const updateRepositoryFullName = `-- name: UpdateRepositoryFullName :one
UPDATE repositories
SET full_name = $2
WHERE github_id = $1
RETURNING id, github_id, full_name, created_at
`

type UpdateRepositoryFullNameParams struct {
	GithubID int64  `json:"github_id"`
	FullName string `json:"full_name"`
}

func (q *Queries) UpdateRepositoryFullName(ctx context.Context, arg UpdateRepositoryFullNameParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepositoryFullName, arg.GithubID, arg.FullName)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}
